### ISSUE TITLE
InvalidOperationException: The calling thread cannot access this object because a different thread owns it

### ISSUE THREAD

**Issue by Bergam64** [sboulema/CodeNav#129]
Hello Samir,

I've recently updated CodeNav to v8.8.29 and I now **often** get the following exception in the Output Window while editing or searching in the current document:

```
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at CodeNav.Helpers.HighlightHelper.<FindItemContainer>d__7.MoveNext() in D:\a\CodeNav\CodeNav\CodeNav.Shared\Helpers\HighlightHelper.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CodeNav.Helpers.HighlightHelper.<>c__DisplayClass3_0.<<Highlight>b__0>d.MoveNext() in D:\a\CodeNav\CodeNav\CodeNav.Shared\Helpers\HighlightHelper.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CodeNav.Helpers.HighlightHelper.<Highlight>d__3.MoveNext() in D:\a\CodeNav\CodeNav\CodeNav.Shared\Helpers\HighlightHelper.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CodeNav.Helpers.HighlightHelper.<HighlightCurrentItem>d__1.MoveNext() in D:\a\CodeNav\CodeNav\CodeNav.Shared\Helpers\HighlightHelper.cs:line 47
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at CodeNav.Helpers.HighlightHelper.<FindItemContainer>d__7.MoveNext() in D:\a\CodeNav\CodeNav\CodeNav.Shared\Helpers\HighlightHelper.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CodeNav.Helpers.HighlightHelper.<>c__DisplayClass3_0.<<Highlight>b__0>d.MoveNext() in D:\a\CodeNav\CodeNav\CodeNav.Shared\Helpers\HighlightHelper.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CodeNav.Helpers.HighlightHelper.<Highlight>d__3.MoveNext() in D:\a\CodeNav\CodeNav\CodeNav.Shared\Helpers\HighlightHelper.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CodeNav.Helpers.HighlightHelper.<HighlightCurrentItem>d__1.MoveNext() in D:\a\CodeNav\CodeNav\CodeNav.Shared\Helpers\HighlightHelper.cs:line 47<---
```

I suspect you're trying to execute some WPF-related operation while not in the main UI Thread.

Note: using Visual Studio 2019 Professional, v16.11.4.

Please fix this. Thanks.

**Comment by sboulema** [comment]
Please try the new release! 🚀

**Comment by Bergam64** [comment]
Hello Samir,

Thanks a lot for the bug fix. It works!

Best regards,
Didier
