### ISSUE TITLE
CodeNav ver 4.2.182 is crushing VS 2017 ver 15.7.1

### ISSUE THREAD

**Issue by Troncho** [sboulema/CodeNav#56]
Hi, since last VS 2017 update (couple of days ago), CodeNave freezes VS 2017, while editing and while debugging, forcing VS to restart.
It's just restarted 3 times in the last hour, while editing a 700 line c# library class.

Again, excellent piece of code!

Thanks,
T

**Comment by sboulema** [comment]
` at CodeNav.Mappers.MethodMapper.MapMethod(MethodBlockSyntax member, CodeViewUserControl control, SemanticModel semanticModel) in C:\projects\codenav\CodeNav\Mappers\MethodMapper.cs:line 68
   at CodeNav.Mappers.SyntaxMapper.MapMember(StatementSyntax member) in C:\projects\codenav\CodeNav\Mappers\SyntaxMapper.cs:line 224
   at CodeNav.Mappers.ClassMapper.MapClass(TypeBlockSyntax member, CodeViewUserControl control, SemanticModel semanticModel, SyntaxTree tree) in C:\projects\codenav\CodeNav\Mappers\ClassMapper.cs:line 72
   at CodeNav.Mappers.SyntaxMapper.MapMember(StatementSyntax member) in C:\projects\codenav\CodeNav\Mappers\SyntaxMapper.cs:line 239
   at CodeNav.Mappers.NamespaceMapper.MapNamespace(NamespaceBlockSyntax member, CodeViewUserControl control, SemanticModel semanticModel) in C:\projects\codenav\CodeNav\Mappers\NamespaceMapper.cs:line 31
   at CodeNav.Mappers.SyntaxMapper.MapMember(StatementSyntax member) in C:\projects\codenav\CodeNav\Mappers\SyntaxMapper.cs:line 239
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CodeNav.Mappers.SyntaxMapper.MapDocument(Document document) in C:\projects\codenav\CodeNav\Mappers\SyntaxMapper.cs:line 135
   at CodeNav.Mappers.SyntaxMapper.MapDocument(Document activeDocument, CodeViewUserControl control, VisualStudioWorkspace workspace) in C:\projects\codenav\CodeNav\Mappers\SyntaxMapper.cs:line 94`

Might be linked to this error in the log, will have a look!

**Comment by sboulema** [comment]
You can try if this release solves your crash: https://github.com/sboulema/CodeNav/releases/tag/v4.2.183
