### ISSUE TITLE
NullReferenceException when clicked on refresh button.

### ISSUE THREAD

**Issue by xperiandri** [sboulema/CodeNav#7]
```
Exception Info: System.NullReferenceException
   at CodeNav.Helpers.VisibilityHelper.SetCodeItemVisibility(System.Collections.Generic.List`1<CodeNav.Models.CodeItem>)
   at CodeNav.CodeViewUserControl.ButtonFilter_OnClick(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```
When clicked on refresh button.

```
Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02036

Installed Version: Enterprise

Architecture and Modeling Tools   00322-90150-00888-AA929
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-90150-00888-AA929
Microsoft Visual Basic 2015

Visual C# 2015   00322-90150-00888-AA929
Microsoft Visual C# 2015

Visual C++ 2015   00322-90150-00888-AA929
Microsoft Visual C++ 2015

Visual F# 2015   00322-90150-00888-AA929
Microsoft Visual F# 2015

Windows Phone SDK 8.0 - ENU   00322-90150-00888-AA929
Windows Phone SDK 8.0 - ENU

.ignore   1.2.71
A language service that makes it painless to handle all types of .ignore files such as .gitignore, .tfignore, etc.

ASP.NET and Web Tools 2015.1   14.1.21111.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9.6   14.0.21111.0
Azure App Service Tools v2.9.6

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.2100.0
Microsoft Azure Data Lake Tools for Visual Studio

BrowseInRemoteGitRepoCommand Extension   1.0
BrowseInRemoteGitRepoCommand Visual Studio Extension Detailed Info

Bundler & Minifier   2.2.307
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

Clear MEF Component Cache   1.3.1
Clears the Visual Studio MEF component cache to fix issues with cache corruption.

CodeLineage   1.0
Information about my package

CodeMaid   10.2.7
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

CodeRush for Roslyn   16.2.4.0
DevExpress CodeRush for Roslyn package.

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DeviceFamily Adaptive XAML Tool Extension   1.0
DeviceFamily Adaptive XAML Tool Visual Studio Extension Detailed Info

EditProj   1.0
This packages allows you to edit project and solution files without the need to unload them first.

EventHandler Naming   1.2.0
EventHandler Naming

Creates better default names for event handling methods.

http://einaregilsson.com/better-eventhandler-names-in-visual-studio-2010/

Extensibility Tools   1.10.188
Contains numerous tools and helpers that makes it easier than ever to build Visual Studio extensions.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

File Icons   2.5
Adds icons for files that are not recognized by Solution Explorer

File Nesting   1.0
Automatically nest files based on file name and enables developers to nest and unnest any file manually

Flatten Packages   1.1.15
Flattens the node_modules folder hierarchy by using the "flatten-packages" npm package behind the scenes. Works with long paths

GhostDoc   5.4.16325.0
GhostDoc automatically generates XML documentation comments.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Markdown Editor   1.10.186
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft .NET Core Tools (Preview 2)   14.1.21111.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Hive Query Language Service   2.2.2100.0
Language service for Hive query

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.41104.6

Multilingual App Toolkit   4.0.1795.0
Multilingual App Toolkit helps you localize your Windows Store app by providing file management, pseudo and machine translation, translation editor, and build integration. http://aka.ms/matinstall

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.179
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

Package Installer   2.0.99
Makes it easier, faster and more convenient than ever to install Bower, npm, Yarn, JSPM, TSD, Typings and NuGet packages to any project

Package Security Alerts   1.0.17
Identifies npm and Bower packages that contains known security vulnerabilities to ensure your project is always using the most secure package versions.

Paket.VisualStudio   1.0
Manage your Paket dependencies from Visual Studio!

Paste-to-target   1.0
Speeds-up Copy/Paste operations by navigating back to the selected target once the Clipboard Copy (Ctrl+C) operation is performed. 

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

QuickLaunch Commands   1.5
Commands search provider integrating with Visual Studio's Quick Launch

SolutionIcon   1.0
Provides a drop-down box to attach to a running process.

SQL Server Analysis Services   13.0.1701.8
Microsoft SQL Server Analysis Services Designer 
Version 13.0.1701.8

SQL Server Data Tools   14.0.61021.0
Microsoft SQL Server Data Tools

Syntax Highlighting Pack   2.5.113
Adds syntax highlighting and snippet support for a wide variety of programming languages such as Clojure, Go, Jade, Lua, Swift, Ruby and many more...

ToastNotifier   1.0
Show Toast Notification when Bulid completed.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.0.6.0
TypeScript tools for Visual Studio

Visual F# Power Tools   2.5.6
A collection of additional commands for F# in Visual Studio

Visual Studio Tools for Universal Windows Apps   14.0.25527.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Compiler   1.11.326
Compiler for LESS, Sass and CoffeeScript files

Web Deploy Parameters Toolkit   1.6
Tools to make it easy to work with parameters in Web Deploy (MSDeploy).  This includes automatically generating a Parameters.xml file from a web.config file, generating SetParameters.xml file from Parameters.xml

WebPack Task Runner   1.5.79
Adds support for WebPack in Visual Studio 2015's Task Runner Explorer.

Xamarin Forms Player   1.0
Preview Xamarin.Forms XAML on devices and simulators, with support for data-binding via JSON dummy view models.

XamlStylerVSPackage   1.0
XAML Styler.
```

**Comment by sboulema** [comment]
Thanks for reporting this bug! Added more nullchecks in the upcoming 1.5 version :)
