### ISSUE TITLE
CodeNav 6.0.351 is broken in VS 2015

### ISSUE THREAD

**Issue by Bergam64** [sboulema/CodeNav#88]
Hello Samir,

hope you are doing well.

I need to report an issue with the latest version of CodeNav (6.0.351), that happens only in VS 2015 (mine is v14.0.25431.01 Update 3) but does NOT on the latest VS 2017 (15.9.9) or latest VS 2019 Preview (4.2). The extension fails to load and the following message is posted to the ActivityLog.xml file:

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Validation, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Validation, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at CodeNav.Helpers.OutliningHelper.GetOutliningManagerService(IServiceProvider serviceProvider)
   at CodeNav.CodeNavFactory.CreateMargin(IWpfTextViewHost wpfTextViewHost, VisualStudioWorkspace visualStudioWorkspace, IServiceProvider serviceProvider, MarginSideEnum side) in D:\a\1\s\CodeNav\CodeNavMarginFactory.cs:line 75
   at CodeNav.CodeNavLeftFactory.CreateMargin(IWpfTextViewHost wpfTextViewHost, IWpfTextViewMargin marginContainer) in D:\a\1\s\CodeNav\CodeNavMarginFactory.cs:line 33
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.<AddMargins>b__25_1(IWpfTextViewMarginProvider mp)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

This happens when opening the first C# file.

Please have a look into this one.

Thanks in advance and best regards from Luxembourg,
Didier Prgomet

**Comment by sboulema** [comment]
Might be linked to #87

**Comment by sboulema** [comment]
Thanks for reporting this bug!

Please try the new release [v6.0.352](https://github.com/sboulema/CodeNav/releases/tag/v6.0.352) 🚀

**Comment by Bergam64** [comment]
Hello Samir!

Congratulations for the impressive response time!

I've just upgraded to v6.0.352 in VS 2015 but the issue is still there, with just a slight change in the logged error:

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Validation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Validation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at CodeNav.Helpers.OutliningHelper.GetOutliningManagerService(IServiceProvider serviceProvider)
   at CodeNav.CodeNavFactory.CreateMargin(IWpfTextViewHost wpfTextViewHost, VisualStudioWorkspace visualStudioWorkspace, IServiceProvider serviceProvider, MarginSideEnum side) in D:\a\1\s\CodeNav\CodeNavMarginFactory.cs:line 75
   at CodeNav.CodeNavLeftFactory.CreateMargin(IWpfTextViewHost wpfTextViewHost, IWpfTextViewMargin marginContainer) in D:\a\1\s\CodeNav\CodeNavMarginFactory.cs:line 33
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.<AddMargins>b__25_1(IWpfTextViewMarginProvider mp)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

So this is not fixed yet.

Good hunting!
Didier

**Comment by sboulema** [comment]
I hate multi-VS support! Thanks for the helpful logs.

Try this release: [v6.0.356](https://github.com/sboulema/CodeNav/releases/tag/v6.0.356) :rocket:

**Comment by Bergam64** [comment]
Hello Samir,

You finally nailed it! I've just tried v6.0.356 in VS 2015 and it's working fine.
I've also retested it in VS 2017 & VS 2019 Preview: no problem.

Thanks again for your remarkable response time!

Oh, one more thing: there's a typo in page "https://github.com/sboulema/CodeNav/blob/master/README.md": "seperate" should be "separate".

Best regards,
Didier
