### ISSUE TITLE
System.Null Reference Exception - CodeNav.Helpers.DocumentHelper.GetNumberOfLines

### ISSUE THREAD

**Issue by MrClyfar** [sboulema/CodeNav#90]
Whilst viewing the diagnostic log in Visual Studio 2019 today, I spotted this exception thrown from CodeNav

```
UNHANDLED EXCEPTIONS FROM PROCESS 22656:
=====================
03/04/2019 14:25:23
System.NullReferenceException: Object reference not set to an instance of an object.
   at CodeNav.Helpers.DocumentHelper.GetNumberOfLines(Document document) in D:\a\1\s\CodeNav\Helpers\DocumentHelper.cs:line 107
   at CodeNav.CodeViewUserControl.IsLargeDocument() in D:\a\1\s\CodeNav\CodeViewUserControl.xaml.cs:line 226
   at CodeNav.CodeNavMargin.<WindowEvents_WindowActivated>d__30.MoveNext() in D:\a\1\s\CodeNav\CodeNavMargin.cs:line 313
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.<>c.<.cctor>b__20_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

My initial guess is that the `document` object is NULL.

https://github.com/sboulema/CodeNav/blob/1673df7f6147d1e92f481d4689d3176c994b872f/CodeNav/Helpers/DocumentHelper.cs#L103

**Comment by sboulema** [comment]
Thanks for reporting! Will look into it.

**Comment by sboulema** [comment]
Grab the new release! 🚀

**Comment by MrClyfar** [comment]
Thank you for responding to, and fixing, this issue so quickly. That was great.

Will this update be made available via Visual Studio Marketplace, so that I can update the extension from inside Visual Studio?

Due to our network security, I cannot download VSIX files directly onto my PC. Thus, I cannot download the VSIX file from the `Releases` area on GitHub.

**Comment by MrClyfar** [comment]
Thank you for responding to, and fixing, this issue so quickly. That was great.

I can see an update for `CodeNav` is available in my Visual Studio, so I will download that now.

Thanks again.
